version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci"
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: swift
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      swift-deps:
        patterns:
          - "*"
    commit-message:
      prefix: "deps"
    labels:
      - dependencies
      - swift
