import ArgumentParser
import ShipItKit
import Foundation

/// Interactive project setup — generates a Shipfile.yml.
///
/// Detects the Xcode workspace/scheme, bundle ID, and team, then writes a starter
/// Shipfile.yml in the current directory.
///
/// ## Usage
/// ```
/// shipit init
/// shipit init --non-interactive --scheme MyApp --bundle-id com.example.myapp
/// ```
struct InitCommand: AsyncParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "init",
        abstract: "Interactive project setup — generates Shipfile.yml"
    )

    @OptionGroup var global: GlobalOptions

    @Option(name: .long, help: "Xcode scheme name")
    var scheme: String?

    @Option(name: .long, help: "App bundle identifier")
    var bundleId: String?

    @Option(name: .long, help: "Apple Developer Team ID")
    var teamId: String?

    @Flag(name: .long, help: "Skip prompts and use provided/detected values")
    var nonInteractive: Bool = false

    func run() async throws {
        let formatter = makeHumanFormatter(global: global)
        formatter.printHeader("ShipItSwifty Init")

        // Auto-detect Xcode workspace/project
        let detectedWorkspace = detectWorkspace()
        let detectedScheme = scheme ?? detectScheme()
        let resolvedBundleId = bundleId
        let resolvedTeamId = teamId ?? ""

        let shipfileContent = """
        # Shipfile.yml — ShipItSwifty configuration
        # Generated by `shipit init` on \(ISO8601DateFormatter().string(from: Date()))
        # All values can be overridden via CLI flags or environment variables.

        app:
          \(detectedWorkspace.map { "workspace: \($0)" } ?? "# workspace: MyApp.xcworkspace")
          scheme: \(detectedScheme ?? "MyApp")
          \(resolvedBundleId.map { "bundle_id: \($0)" } ?? "# bundle_id: com.example.myapp  # Optional; auto-detected from Xcode if omitted")
          \(resolvedTeamId.isEmpty ? "# team_id: ABCDE12345" : "team_id: \(resolvedTeamId)")

        app_store_connect:
          key_id: ${ASC_KEY_ID}
          issuer_id: ${ASC_ISSUER_ID}
          # key_path: ./.secrets/AuthKey.p8  # Local dev only; keep out of git

        code_signing:
          type: automatic
          # Use `vault` or `manual` if you want ShipIt-managed certificates/profiles.
          # storage: git
          # git_url: git@github.com:yourteam/certs.git
          # profile_type: appstore

        build:
          configuration: Release
          derived_data_path: ./DerivedData

        archive:
          export_method: app-store
          include_symbols: true
          output_path: ./build/\(detectedScheme ?? "MyApp").xcarchive

        export:
          output_directory: ./build/export

        testflight:
          skip_waiting_for_build_processing: false
          distribute_external: true
          changelog: "Bug fixes and improvements"

        metadata:
          directory: ./metadata
          submit_for_review: false
          automatic_release: false
          phased_release: true

        versioning:
          strategy: sequential
          source: xcodeproj

        notifications:
          slack:
            webhook_url: ${SLACK_WEBHOOK_URL}
            channel: "#releases"
            on_success: true
            on_failure: true

        # Named workflows for `shipit run <workflow>`
        workflows:
          beta:
            - action: version
              options: { bump: build }
            - action: archive
              options: { configuration: Release, export_method: app-store }
            - action: export
              options: { output_directory: ./build/export }
            - action: testflight
              options: { groups: ["Internal QA"] }
            - action: notify
              options:
                slack:
                  message: "Beta uploaded!"

          release:
            - action: version
              options: { bump: build }
            - action: archive
              options: { configuration: Release, export_method: app-store }
            - action: export
              options: { output_directory: ./build/export }
            - action: metadata
              options: { push: true }
            - action: upload
              options: { submit_for_review: true, phased_release: true }
            - action: notify
              options:
                slack:
                  message: "App submitted for review!"
        """

        let outputPath = "./Shipfile.yml"

        if FileManager.default.fileExists(atPath: outputPath) && !nonInteractive {
            formatter.printWarning("Shipfile.yml already exists at \(outputPath). Use --non-interactive to overwrite without prompting.")
        }

        try shipfileContent.write(toFile: outputPath, atomically: true, encoding: .utf8)
        formatter.printSuccess("Created Shipfile.yml at \(outputPath)")
        formatter.print("")
        formatter.print("Next steps:")
        formatter.print("  1. Edit Shipfile.yml to fit your project settings")
        formatter.print("  2. Set up App Store Connect credentials:")
        formatter.print("     Required for ASC API actions: ASC_KEY_ID + ASC_ISSUER_ID + one private key source")
        formatter.print("     Skip this if you only use build/test/archive/export locally")
        formatter.print("     App Store Connect > Users and Access > Integrations > App Store Connect API")
        formatter.print("     export ASC_KEY_ID=your-key-id")
        formatter.print("     export ASC_ISSUER_ID=your-issuer-id")
        formatter.print("     export ASC_PRIVATE_KEY=$(cat ~/AuthKey_xxx.p8)  # or use ASC_PRIVATE_KEY_PATH")
        formatter.print("  3. Set up code signing:")
        formatter.print("     shipit sign init --git-url git@github.com:yourteam/certs.git")
        formatter.print("     shipit sign sync --type appstore")
        formatter.print("  4. Run your first workflow:")
        formatter.print("     shipit run beta")
    }

    // MARK: - Detection Helpers

    private func detectWorkspace() -> String? {
        let fm = FileManager.default
        let contents = (try? fm.contentsOfDirectory(atPath: ".")) ?? []
        return contents.first { $0.hasSuffix(".xcworkspace") }
    }

    private func detectScheme() -> String? {
        let fm = FileManager.default
        let contents = (try? fm.contentsOfDirectory(atPath: ".")) ?? []
        if let workspace = contents.first(where: { $0.hasSuffix(".xcworkspace") }) {
            return (workspace as NSString).deletingPathExtension
        }
        if let project = contents.first(where: { $0.hasSuffix(".xcodeproj") }) {
            return (project as NSString).deletingPathExtension
        }
        return nil
    }
}
