import Foundation
import OSLog
import SwiftyShell

/// Parses Android code coverage data from a JaCoCo XML report.
///
/// ShipIt reads JaCoCo's standard XML report format — generated by Gradle's
/// `jacocoTestReport` task — and decodes it into typed ``CoverageTarget`` values.
/// No third-party tools beyond JaCoCo itself are needed.
///
/// Typical report location: `app/build/reports/jacoco/test/jacocoTestReport.xml`
///
/// A JaCoCo XML report has this top-level structure:
/// ```xml
/// <report name="…">
///   <package name="com/example/feature">
///     <class name="com/example/feature/ViewModel" sourcefilename="ViewModel.kt">
///       <method …><counter type="LINE" …/></method>
///       <counter type="LINE" covered="42" missed="8"/>
///     </class>
///     <sourcefile name="ViewModel.kt">
///       <counter type="LINE" covered="42" missed="8"/>
///     </sourcefile>
///     <counter type="LINE" covered="180" missed="40"/>
///   </package>
///   <counter type="LINE" covered="900" missed="200"/>
/// </report>
/// ```
///
/// ShipIt groups packages into logical modules (the top-level component of the
/// package name, e.g. `com/example/featureA` → `featureA`).
struct AndroidCoverageParser: Sendable {

    let logger: Logger

    // MARK: - Parse

    /// Parse all modules from the JaCoCo XML report at the given path.
    ///
    /// - Parameter reportPath: Absolute or project-relative path to the XML report.
    /// - Returns: Array of ``CoverageTarget`` values (one per discovered module).
    /// - Throws: ``ShipItError/invalidConfiguration(reason:)`` when parsing fails.
    func parse(reportPath: String) async throws -> [CoverageTarget] {
        logger.debug("Parsing JaCoCo XML report at \(reportPath)")

        guard let data = FileManager.default.contents(atPath: reportPath) else {
            throw ShipItError.invalidConfiguration(
                reason: "Could not read JaCoCo report at \(reportPath). " +
                "Run `./gradlew jacocoTestReport` to generate it first."
            )
        }

        let parser = JacocoXMLParser(data: data)
        let rawPackages = try parser.parse()

        // Group packages into modules by their top-level component
        let grouped = groupIntoModules(rawPackages)

        logger.debug("Parsed \(grouped.count) modules from \(rawPackages.count) JaCoCo packages")
        return grouped
    }

    // MARK: - Module Grouping

    /// Aggregate JaCoCo `<package>` elements into logical modules.
    ///
    /// A JaCoCo package name like `com/example/featureA/ui` maps to module `featureA`
    /// (the component after the org/domain prefix).
    ///
    /// If there is only one level of packages (flat project), each package becomes its
    /// own module named by its full path.
    private func groupIntoModules(_ packages: [JacocoPackage]) -> [CoverageTarget] {
        // Determine the common prefix depth (org prefix, e.g. "com/example")
        let prefixDepth = detectOrgPrefixDepth(packages: packages)

        var moduleMap: [String: (coveredLines: Int, executableLines: Int, files: [CoverageFile])] = [:]

        for package in packages {
            let moduleName = extractModuleName(from: package.name, prefixDepth: prefixDepth)

            var existing = moduleMap[moduleName] ?? (coveredLines: 0, executableLines: 0, files: [])
            existing.coveredLines += package.coveredLines
            existing.executableLines += package.executableLines

            let newFiles = package.sourceFiles.map { sf in
                CoverageFile(
                    path: "\(package.name)/\(sf.name)",
                    lineCoverage: sf.executableLines > 0
                        ? ((Double(sf.coveredLines) / Double(sf.executableLines)) * 100.0).rounded(toDecimalPlaces: 1)
                        : 0.0,
                    coveredLines: sf.coveredLines,
                    executableLines: sf.executableLines
                )
            }
            existing.files.append(contentsOf: newFiles)
            moduleMap[moduleName] = existing
        }

        return moduleMap.map { name, data in
            let coverage = data.executableLines > 0
                ? (Double(data.coveredLines) / Double(data.executableLines)) * 100.0
                : 0.0
            return CoverageTarget(
                name: name,
                lineCoverage: coverage.rounded(toDecimalPlaces: 1),
                coveredLines: data.coveredLines,
                executableLines: data.executableLines,
                files: data.files
            )
        }.sorted { $0.name < $1.name }
    }

    /// Detect the depth of the org prefix (e.g. `com/example` = depth 2).
    ///
    /// If all packages share the same 2-component prefix, we skip that many
    /// components. Falls back to depth 0 (no prefix skipping) for flat projects.
    private func detectOrgPrefixDepth(packages: [JacocoPackage]) -> Int {
        guard !packages.isEmpty else { return 0 }

        // Common Android convention: com/<company> or org/<company> = depth 2
        let domainPrefixes = ["com", "org", "io", "net", "dev"]
        let firstComponents = packages.map { $0.name.components(separatedBy: "/") }

        // Check if all packages share the same first component that is a known domain prefix
        let firstComponents0 = firstComponents.compactMap { $0.first }
        let uniqueFirst = Set(firstComponents0)
        if uniqueFirst.count == 1, let first = uniqueFirst.first, domainPrefixes.contains(first) {
            // All share a domain prefix — use depth 2 (com/example)
            let secondComponents = firstComponents.compactMap { $0.count > 1 ? $0[1] : nil }
            let uniqueSecond = Set(secondComponents)
            if uniqueSecond.count == 1 {
                return 2
            }
            return 1
        }
        return 0
    }

    private func extractModuleName(from packageName: String, prefixDepth: Int) -> String {
        let components = packageName.components(separatedBy: "/")
        guard components.count > prefixDepth else {
            return packageName
        }
        return components[prefixDepth]
    }
}

// MARK: - JaCoCo XML Parser

/// SAX-style parser for the JaCoCo XML report format.
private final class JacocoXMLParser: NSObject, XMLParserDelegate, @unchecked Sendable {

    private let data: Data
    private var packages: [JacocoPackage] = []
    private var currentPackage: MutablePackage?
    private var currentSourceFile: MutableSourceFile?
    private var parseError: Error?

    init(data: Data) {
        self.data = data
    }

    func parse() throws -> [JacocoPackage] {
        let xmlParser = XMLParser(data: data)
        xmlParser.delegate = self
        xmlParser.parse()

        if let error = parseError {
            throw ShipItError.invalidConfiguration(
                reason: "JaCoCo XML parse error: \(error.localizedDescription)"
            )
        }

        return packages
    }

    // MARK: - XMLParserDelegate

    func parser(
        _ parser: XMLParser,
        didStartElement elementName: String,
        namespaceURI: String?,
        qualifiedName qName: String?,
        attributes attributeDict: [String: String] = [:]
    ) {
        switch elementName {
        case "package":
            if let name = attributeDict["name"] {
                currentPackage = MutablePackage(name: name)
            }

        case "sourcefile":
            if let name = attributeDict["name"] {
                currentSourceFile = MutableSourceFile(name: name)
            }

        case "counter":
            guard attributeDict["type"] == "LINE" else { return }
            let covered = Int(attributeDict["covered"] ?? "0") ?? 0
            let missed = Int(attributeDict["missed"] ?? "0") ?? 0

            if currentSourceFile != nil {
                // Inside a <sourcefile>
                currentSourceFile?.coveredLines += covered
                currentSourceFile?.executableLines += covered + missed
            } else if currentPackage != nil {
                // Inside a <package> but outside <sourcefile> — package-level counter
                currentPackage?.packageCoveredLines += covered
                currentPackage?.packageExecutableLines += covered + missed
            }
            // Ignore report-level counters (outside any package)

        default:
            break
        }
    }

    func parser(
        _ parser: XMLParser,
        didEndElement elementName: String,
        namespaceURI: String?,
        qualifiedName qName: String?
    ) {
        switch elementName {
        case "sourcefile":
            if let sf = currentSourceFile {
                currentPackage?.sourceFiles.append(JacocoSourceFile(
                    name: sf.name,
                    coveredLines: sf.coveredLines,
                    executableLines: sf.executableLines
                ))
            }
            currentSourceFile = nil

        case "package":
            if let pkg = currentPackage {
                packages.append(JacocoPackage(
                    name: pkg.name,
                    coveredLines: pkg.packageCoveredLines,
                    executableLines: pkg.packageExecutableLines,
                    sourceFiles: pkg.sourceFiles
                ))
            }
            currentPackage = nil

        default:
            break
        }
    }

    func parser(_ parser: XMLParser, parseErrorOccurred parseError: Error) {
        self.parseError = parseError
    }
}

// MARK: - Mutable Builder Types (used during SAX parsing)

private final class MutablePackage: @unchecked Sendable {
    let name: String
    var packageCoveredLines: Int = 0
    var packageExecutableLines: Int = 0
    var sourceFiles: [JacocoSourceFile] = []

    init(name: String) { self.name = name }
}

private final class MutableSourceFile: @unchecked Sendable {
    let name: String
    var coveredLines: Int = 0
    var executableLines: Int = 0

    init(name: String) { self.name = name }
}

// MARK: - Immutable Value Types

private struct JacocoPackage: Sendable {
    let name: String
    let coveredLines: Int
    let executableLines: Int
    let sourceFiles: [JacocoSourceFile]
}

private struct JacocoSourceFile: Sendable {
    let name: String
    let coveredLines: Int
    let executableLines: Int
}

// MARK: - Double helper

private extension Double {
    func rounded(toDecimalPlaces places: Int) -> Double {
        let multiplier = pow(10.0, Double(places))
        return (self * multiplier).rounded() / multiplier
    }
}
