import Foundation
import OSLog
import SwiftyShell

/// Reads and summarizes native coverage artifacts produced by a prior test run.
///
/// ShipItSwifty does **not** generate coverage data itself — it wraps and
/// normalises the artifacts that your platform toolchain already produces:
/// - **iOS**: `.xcresult` bundles created by `xcodebuild test -enableCodeCoverage YES`
/// - **Android**: JaCoCo XML reports generated by Gradle's `jacocoTestReport` task
///
/// ## Usage
/// ```swift
/// // iOS — infer xcresult from config
/// let result = try await CoverageAction().run(
///     with: .init(firstPartyOnly: true, format: .text),
///     context: context
/// )
/// print("Overall: \(result.overallLineCoverage)%")
///
/// // Android — explicit report path
/// let result = try await CoverageAction().run(
///     with: .init(reportPath: "./app/build/reports/jacoco/test/jacocoTestReport.xml"),
///     context: androidContext
/// )
/// for module in result.modules { print("\(module.name): \(module.lineCoverage)%") }
/// ```
///
/// ## Topics
/// ### Configuration
/// - ``Options``
/// ### Results
/// - ``Result``
/// - ``CoverageTarget``
/// - ``CoverageFile``
public struct CoverageAction: Action {
    public static let name = "coverage"
    public static let description = "Read and summarize native coverage artifacts (iOS: xcresult/xccov, Android: JaCoCo XML)"

    private let logger = Logger.forType(subsystem: "ShipItSwifty", CoverageAction.self)

    public init() {}

    // MARK: - Options

    /// Configuration options for the coverage action.
    public struct Options: Codable, Sendable {
        // MARK: Shared options

        /// Output format. Defaults to `.text`.
        public var format: CoverageFormat?

        /// Only include first-party targets/modules. Suppresses test bundles,
        /// vendored frameworks, and Swift-package dependencies. Defaults to `true`.
        public var firstPartyOnly: Bool?

        /// Emit a single-line overall summary and return, skipping per-target detail.
        public var summary: Bool?

        /// Include per-target / per-module breakdown in the output.
        public var showTargets: Bool?

        /// Include per-file breakdown in the output.
        public var showFiles: Bool?

        /// Include per-function breakdown in the output (where available).
        public var showFunctions: Bool?

        /// Target/module names to explicitly include (overrides first-party filter).
        public var includeTargets: [String]?

        /// Target/module names to exclude from results.
        public var excludeTargets: [String]?

        /// Sort order for the output. Defaults to `.coverage` (lowest first, most actionable).
        public var sort: CoverageSort?

        /// Limit the number of targets/modules shown. No limit when `nil`.
        public var limit: Int?

        // MARK: iOS-specific options

        /// Explicit path to a `.xcresult` bundle.
        /// When omitted, ShipIt auto-discovers the bundle from config (`resultBundlePath`)
        /// or the well-known default `./build/<scheme>-tests.xcresult`.
        public var xcresultPath: String?

        // MARK: Android-specific options

        /// Explicit path to a JaCoCo XML report.
        /// When omitted, ShipIt searches common Gradle output paths.
        public var reportPath: String?

        public init(
            format: CoverageFormat? = nil,
            firstPartyOnly: Bool? = nil,
            summary: Bool? = nil,
            showTargets: Bool? = nil,
            showFiles: Bool? = nil,
            showFunctions: Bool? = nil,
            includeTargets: [String]? = nil,
            excludeTargets: [String]? = nil,
            sort: CoverageSort? = nil,
            limit: Int? = nil,
            xcresultPath: String? = nil,
            reportPath: String? = nil
        ) {
            self.format = format
            self.firstPartyOnly = firstPartyOnly
            self.summary = summary
            self.showTargets = showTargets
            self.showFiles = showFiles
            self.showFunctions = showFunctions
            self.includeTargets = includeTargets
            self.excludeTargets = excludeTargets
            self.sort = sort
            self.limit = limit
            self.xcresultPath = xcresultPath
            self.reportPath = reportPath
        }
    }

    // MARK: - Result

    /// Summary of coverage across all selected targets/modules.
    public struct Result: Codable, Sendable {
        /// Target platform that produced these results.
        public let platform: String

        /// Path to the coverage source artifact (xcresult or XML report).
        public let source: String

        /// Overall line coverage percentage across all selected targets/modules.
        public let overallLineCoverage: Double

        /// Per-target (iOS) or per-module (Android) coverage entries.
        public let targets: [CoverageTarget]

        /// Total covered lines across all selected entries.
        public let coveredLines: Int

        /// Total executable lines across all selected entries.
        public let executableLines: Int

        /// Whether first-party filtering was applied.
        public let firstPartyOnly: Bool

        public init(
            platform: String,
            source: String,
            overallLineCoverage: Double,
            targets: [CoverageTarget],
            coveredLines: Int,
            executableLines: Int,
            firstPartyOnly: Bool
        ) {
            self.platform = platform
            self.source = source
            self.overallLineCoverage = overallLineCoverage
            self.targets = targets
            self.coveredLines = coveredLines
            self.executableLines = executableLines
            self.firstPartyOnly = firstPartyOnly
        }
    }

    // MARK: - Run

    public func run(with options: Options, context: ActionContext) async throws -> Result {
        switch context.platform {
        case .ios:
            return try await runIOS(options: options, context: context)
        case .android:
            return try await runAndroid(options: options, context: context)
        }
    }

    // MARK: - iOS

    private func runIOS(options: Options, context: ActionContext) async throws -> Result {
        let xcresultPath = resolveXCResultPath(options: options, config: context.config)
        guard let xcresultPath else {
            throw ShipItError.invalidConfiguration(
                reason: """
                No .xcresult bundle found. Provide --xcresult <path>, or run \
                `shipit test` with enable_code_coverage: true first. \
                ShipIt auto-discovers ./build/<scheme>-tests.xcresult when app.scheme is set.
                """
            )
        }

        logger.info("Reading iOS coverage from \(xcresultPath)")

        let parser = IOSCoverageParser(shell: context.shell, logger: logger)
        let targets = try await parser.parse(xcresultPath: xcresultPath)

        let firstPartyOnly = options.firstPartyOnly ?? true
        let filtered = applyFilters(
            targets: targets,
            firstPartyOnly: firstPartyOnly,
            include: options.includeTargets,
            exclude: options.excludeTargets
        )

        let (covered, executable, overall) = aggregateCoverage(filtered)

        logger.info("iOS coverage parsed: \(String(format: "%.1f", overall))% overall across \(filtered.count) targets")

        return Result(
            platform: "ios",
            source: xcresultPath,
            overallLineCoverage: overall,
            targets: filtered,
            coveredLines: covered,
            executableLines: executable,
            firstPartyOnly: firstPartyOnly
        )
    }

    // MARK: - Android

    private func runAndroid(options: Options, context: ActionContext) async throws -> Result {
        let reportPath = options.reportPath ?? discoverAndroidReport(context: context)
        guard let reportPath else {
            throw ShipItError.invalidConfiguration(
                reason: """
                No JaCoCo XML report found. Provide --report <path>, or run \
                `./gradlew jacocoTestReport` first. \
                ShipIt searches common paths: \
                app/build/reports/jacoco/test/jacocoTestReport.xml and \
                build/reports/jacoco/test/jacocoTestReport.xml.
                """
            )
        }

        logger.info("Reading Android coverage from \(reportPath)")

        let parser = AndroidCoverageParser(logger: logger)
        let targets = try await parser.parse(reportPath: reportPath)

        let firstPartyOnly = options.firstPartyOnly ?? true
        let filtered = applyFilters(
            targets: targets,
            firstPartyOnly: firstPartyOnly,
            include: options.includeTargets,
            exclude: options.excludeTargets
        )

        let (covered, executable, overall) = aggregateCoverage(filtered)

        logger.info("Android coverage parsed: \(String(format: "%.1f", overall))% overall across \(filtered.count) modules")

        return Result(
            platform: "android",
            source: reportPath,
            overallLineCoverage: overall,
            targets: filtered,
            coveredLines: covered,
            executableLines: executable,
            firstPartyOnly: firstPartyOnly
        )
    }

    // MARK: - Path Discovery

    private func resolveXCResultPath(options: Options, config: ResolvedConfig) -> String? {
        // 1. Explicit option wins
        if let explicit = options.xcresultPath { return explicit }

        // 2. Well-known default: ./build/<scheme>-tests.xcresult
        //    (matches the auto-derived path that TestAction uses when
        //     enable_code_coverage: true and result_bundle_path is unset)
        if let scheme = config.appScheme {
            let defaultPath = "./build/\(scheme)-tests.xcresult"
            if FileManager.default.fileExists(atPath: defaultPath) {
                return defaultPath
            }
        }

        // 3. Glob ./build/ for any .xcresult (catches user-specified paths)
        if let found = firstXCResult(in: "./build") { return found }

        return nil
    }

    private func firstXCResult(in directory: String) -> String? {
        guard let enumerator = FileManager.default.enumerator(atPath: directory) else {
            return nil
        }
        for case let path as String in enumerator {
            if path.hasSuffix(".xcresult") {
                return (directory as NSString).appendingPathComponent(path)
            }
        }
        return nil
    }

    private func discoverAndroidReport(context: ActionContext) -> String? {
        let module = context.config.androidModule
        let candidates = [
            "\(module)/build/reports/jacoco/test/jacocoTestReport.xml",
            "\(module)/build/reports/jacoco/jacocoTestReport.xml",
            "build/reports/jacoco/test/jacocoTestReport.xml",
            "build/reports/jacoco/jacocoTestReport.xml",
            "\(module)/build/reports/coverage/test/report.xml",
        ]
        return candidates.first { FileManager.default.fileExists(atPath: $0) }
    }

    // MARK: - Filtering

    private func applyFilters(
        targets: [CoverageTarget],
        firstPartyOnly: Bool,
        include: [String]?,
        exclude: [String]?
    ) -> [CoverageTarget] {
        var result = targets

        // Suppress 0/0 entries (no executable lines — useless noise)
        result = result.filter { $0.executableLines > 0 }

        if let include {
            // Explicit include list overrides first-party filter entirely.
            let includeSet = Set(include)
            result = result.filter { includeSet.contains($0.name) }
        } else if firstPartyOnly {
            // Only apply first-party classification when no explicit include list is given.
            result = result.filter { target in
                let verdict = classifyTarget(target)
                logger.debug("[\(target.name)] first-party classification: \(verdict.isFirstParty ? "included" : "excluded") (\(verdict.reason))")
                return verdict.isFirstParty
            }
        }

        if let exclude {
            let excludeSet = Set(exclude)
            result = result.filter { !excludeSet.contains($0.name) }
        }

        return result
    }

    // MARK: - First-Party Classification

    /// Result of classifying a target as first-party or third-party.
    private struct ClassificationVerdict {
        let isFirstParty: Bool
        let reason: String
    }

    /// Classify a coverage target using path-based detection first, then name heuristics.
    ///
    /// **Precedence:**
    /// 1. Path-based: if any source file in the target resolves to a SwiftPM
    ///    checkout path (`SourcePackages/checkouts/`, `SourcePackages/artifacts/`,
    ///    or `checkouts/` inside DerivedData), the target is third-party.
    /// 2. Path-based: if all source files resolve under the current working directory
    ///    (and not DerivedData), the target is first-party.
    /// 3. Name heuristic fallback: applied when no file paths are available.
    private func classifyTarget(_ target: CoverageTarget) -> ClassificationVerdict {
        // Path-based classification when file information is available
        if !target.files.isEmpty {
            // Check if any source file originates from a SwiftPM checkout location.
            // xccov reports absolute paths, so SPM deps always have DerivedData/…/SourcePackages
            // or a similar checkout path component.
            let spmPathComponents = [
                "/SourcePackages/checkouts/",
                "/SourcePackages/artifacts/",
                "/SourcePackages/workspace-state",
                "/.build/checkouts/",
            ]
            let hasSPMFile = target.files.contains { file in
                spmPathComponents.contains(where: { file.path.contains($0) })
            }
            if hasSPMFile {
                return ClassificationVerdict(isFirstParty: false, reason: "source files in SPM SourcePackages/checkouts path")
            }

            // Check if source files live under DerivedData (but not in SourcePackages).
            // Targets whose *all* files are in DerivedData (e.g. generated code stubs)
            // are treated as third-party to avoid noise. Targets with at least one
            // non-DerivedData file are considered project-owned.
            let derivedDataComponent = "/DerivedData/"
            let allInDerivedData = target.files.allSatisfy { $0.path.contains(derivedDataComponent) }
            if allInDerivedData {
                return ClassificationVerdict(isFirstParty: false, reason: "all source files under DerivedData (not in project sources)")
            }

            // At least one file is outside DerivedData → project-owned source.
            let hasProjectFile = target.files.contains { !$0.path.contains(derivedDataComponent) }
            if hasProjectFile {
                return ClassificationVerdict(isFirstParty: true, reason: "source files found in project directory")
            }
        }

        // Name-based fallback when no file path information is available.
        return classifyByName(target.name)
    }

    /// Name-based heuristic: flag well-known vendor/test patterns as third-party.
    /// Used as a fallback when no file paths are available.
    private func classifyByName(_ name: String) -> ClassificationVerdict {
        let lower = name.lowercased()
        // Test bundles
        if lower.hasSuffix("tests") || lower.hasSuffix("test") || lower.hasSuffix("uitests") {
            return ClassificationVerdict(isFirstParty: false, reason: "name matches test bundle suffix")
        }
        // Swift package dependencies (PackageFrameworks, .build paths)
        if lower.contains("packageframeworks") || lower.contains(".build/") {
            return ClassificationVerdict(isFirstParty: false, reason: "name contains SPM package path component")
        }
        // Common vendor prefixes
        let vendorPrefixes = [
            "google", "firebase", "facebook", "realm", "alamofire",
            "kingfisher", "snapkit", "rxswift", "rxcocoa", "combine",
            "swift-", "swiftui", "xctest", "pods-", "rncxx",
        ]
        for prefix in vendorPrefixes {
            if lower.hasPrefix(prefix) {
                return ClassificationVerdict(isFirstParty: false, reason: "name matches known vendor prefix '\(prefix)'")
            }
        }
        return ClassificationVerdict(isFirstParty: true, reason: "no known third-party name pattern matched (name heuristic)")
    }

    // MARK: - Aggregation

    private func aggregateCoverage(_ targets: [CoverageTarget]) -> (covered: Int, executable: Int, overall: Double) {
        let covered = targets.reduce(0) { $0 + $1.coveredLines }
        let executable = targets.reduce(0) { $0 + $1.executableLines }
        let overall = executable > 0 ? (Double(covered) / Double(executable)) * 100.0 : 0.0
        return (covered, executable, overall.rounded(toDecimalPlaces: 1))
    }
}

// MARK: - Supporting Types

/// Coverage entry for a single target (iOS) or module/package (Android).
public struct CoverageTarget: Codable, Sendable {
    /// Target or module name.
    public let name: String

    /// Line coverage percentage (0–100).
    public let lineCoverage: Double

    /// Number of covered lines.
    public let coveredLines: Int

    /// Total executable lines.
    public let executableLines: Int

    /// Per-file breakdown. Empty when `--files` is not requested.
    public let files: [CoverageFile]

    public init(
        name: String,
        lineCoverage: Double,
        coveredLines: Int,
        executableLines: Int,
        files: [CoverageFile] = []
    ) {
        self.name = name
        self.lineCoverage = lineCoverage
        self.coveredLines = coveredLines
        self.executableLines = executableLines
        self.files = files
    }
}

/// Coverage entry for a single source file.
public struct CoverageFile: Codable, Sendable {
    /// File path (relative to the project root when available).
    public let path: String

    /// Line coverage percentage (0–100).
    public let lineCoverage: Double

    /// Number of covered lines.
    public let coveredLines: Int

    /// Total executable lines.
    public let executableLines: Int

    public init(path: String, lineCoverage: Double, coveredLines: Int, executableLines: Int) {
        self.path = path
        self.lineCoverage = lineCoverage
        self.coveredLines = coveredLines
        self.executableLines = executableLines
    }
}

/// Output format for the coverage report.
public enum CoverageFormat: String, Codable, Sendable {
    case text
    case json
    case markdown
}

/// Sort order for coverage results.
public enum CoverageSort: String, Codable, Sendable {
    /// Sort by coverage ascending (lowest first — most actionable).
    case coverage
    /// Sort alphabetically by name.
    case name
}

// MARK: - Double Rounding Helper

private extension Double {
    func rounded(toDecimalPlaces places: Int) -> Double {
        let multiplier = pow(10.0, Double(places))
        return (self * multiplier).rounded() / multiplier
    }
}
